version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: expense_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: >
      sh -c '
      until mysqladmin ping -h db --silent; do
        echo " Waiting for MySQL...";
        sleep 2;
      done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      '
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/vite-project
    ports:
      - "3000:80"
    depends_on:
      - web
    environment:
      - NODE_ENV=production

volumes:
  mysql_data:
  media:
